export const ThemeKaluza = {
  fontFamilyText: "'Open Sans', sans-serif",
  fontSize: "1.1em",
  lineHeight: "1.40",
  mainBgColor: "#061B32",
  lightColorText: "#8FA1BD",
  titleColor: "#57d5f4",
  textColor: "#333",
  onLineColor: "#0a9928",
  offLineColor: "#ff0000",
  smallMargin: "5px",
  mediumMargin: "10px",
  largeMargin: "20px",
  xLargeMargin: "40px",
  xxLargeMargin: "80px",
  smallPadding: "5px",
  mediumPadding: "10px",
  largePadding: "20px",
  xLargePadding: "40px",
  xxLargePadding: "80px",
  filterBarHeight: "60px",
  deviceIconSize: "80px",
  onlineStatusIconSize: "12px",
  chargeBgColor: "#57d5f4",
  menuHoverColor: "#57d5f4",
};
